### ISSUE TITLE
Create and update  favicon

### ISSUE THREAD

**Issue by paragasu** [jurismanager/jurismanager-web#2]
Font: Avenir

![jurismanager](https://user-images.githubusercontent.com/27353/82585567-c63ef280-9bc8-11ea-8eee-29043d218065.png)

Favicon can be one orange circle :)

**Comment by izahshahirah** [comment]
[juris-favicon.ico.zip](https://github.com/phisoft/jurismanager-web/files/4665673/juris-favicon.ico.zip)

**Comment by izahshahirah** [comment]
[Favicon-app.zip](https://github.com/jurismanager/jurismanager-web/files/4755969/Favicon-app.zip)

**Comment by paragasu** [comment]
@izahshahirah can you use orange circle only for favicon?

**Comment by izahshahirah** [comment]
Orange circle favicon.

[juris-favicon.ico.zip](https://github.com/jurismanager/jurismanager-web/files/4762101/juris-favicon.ico.zip)
