### ISSUE TITLE
Redesign pricing section

### ISSUE THREAD

**Issue by paragasu** [jurismanager/jurismanager-web#30]
I think this part doesn't blend with the rest of the site

<img width="1680" alt="Screenshot 2020-06-24 at 10 12 24 AM" src="https://user-images.githubusercontent.com/27353/85489903-5c6c9b00-b603-11ea-857d-25ff36357ea3.png">

Need to improve this part

**Comment by izahshahirah** [comment]
done 

<img width="1758" alt="Screenshot 2020-12-21 at 1 31 50 PM" src="https://user-images.githubusercontent.com/60636305/102742844-ec13bc00-4390-11eb-935f-88e6d5b8f1d5.png">
